from __future__ import annotations

from app.domain.entities.component import ComponentCategory as C
from app.seed.catalog.builder import P, component, pins

TWO = pins(("a", P.PASSIVE), ("b", P.PASSIVE))
DIODE = pins(("anode", P.PASSIVE), ("cathode", P.PASSIVE))
POLAR = pins(("+", P.PASSIVE), ("-", P.PASSIVE))
BJT = pins(("base", P.INPUT), ("collector", P.PASSIVE), ("emitter", P.PASSIVE))
FET = pins(("gate", P.INPUT), ("drain", P.PASSIVE), ("source", P.PASSIVE))
REGULATOR = pins(("vin", P.POWER), ("gnd", P.GROUND), ("vout", P.POWER))

PASSIVES = [
    component(
        "resistor",
        "Resistor",
        C.PASSIVE,
        TWO,
        subcategory="resistor",
        default_params={"resistance": 330, "power_rating": 0.25},
        tags=["basic"],
    ),
    component(
        "potentiometer",
        "Potentiometer",
        C.PASSIVE,
        pins(("1", P.PASSIVE), ("wiper", P.PASSIVE), ("3", P.PASSIVE)),
        subcategory="resistor",
        default_params={"resistance": 10000, "position": 0.5},
    ),
    component(
        "voltmeter",
        "Voltmeter",
        C.PASSIVE,
        pins(("+", P.PASSIVE), ("-", P.PASSIVE)),
        subcategory="meter",
        description="Ideal voltmeter — wire + and - across two points to read the voltage between them",
        tags=["instrument", "measure"],
    ),
    component(
        "ammeter",
        "Ammeter",
        C.PASSIVE,
        pins(("in", P.PASSIVE), ("out", P.PASSIVE)),
        subcategory="meter",
        description="Ideal ammeter — insert in series to read the current flowing through it",
        tags=["instrument", "measure"],
    ),
    component(
        "capacitor",
        "Ceramic Capacitor",
        C.PASSIVE,
        TWO,
        subcategory="capacitor",
        default_params={"capacitance": "100nF"},
    ),
    component(
        "electrolytic_cap",
        "Electrolytic Capacitor",
        C.PASSIVE,
        POLAR,
        subcategory="capacitor",
        default_params={"capacitance": "10uF"},
    ),
    component(
        "inductor",
        "Inductor",
        C.PASSIVE,
        TWO,
        subcategory="inductor",
        default_params={"inductance": "10uH"},
    ),
    component(
        "led",
        "LED",
        C.PASSIVE,
        DIODE,
        subcategory="diode",
        default_params={"color": "red", "max_current": 0.02},
        tags=["basic"],
    ),
    component(
        "rgb_led",
        "RGB LED",
        C.PASSIVE,
        pins(("r", P.PASSIVE), ("g", P.PASSIVE), ("b", P.PASSIVE), ("common", P.GROUND)),
        subcategory="diode",
        description="Common-cathode RGB LED; drive each colour leg through a resistor",
        default_params={"max_current": 0.02},
        tags=["basic"],
    ),
    component("diode", "Diode 1N4148", C.PASSIVE, DIODE, subcategory="diode"),
    component(
        "push_button",
        "Push Button",
        C.PASSIVE,
        TWO,
        subcategory="switch",
        default_params={"pressed": 0},
        tags=["basic", "interactive"],
    ),
    component(
        "push_button_nc",
        "Push Button (NC)",
        C.PASSIVE,
        TWO,
        subcategory="switch",
        description="Normally-closed momentary button; opens only while pressed",
        default_params={"pressed": 0, "normally_closed": 1},
        tags=["interactive"],
    ),
    component(
        "toggle_switch",
        "Toggle Switch (SPST)",
        C.PASSIVE,
        TWO,
        subcategory="switch",
        description="Latching on/off switch",
        default_params={"closed": 0},
        tags=["basic", "interactive"],
    ),
    component(
        "spdt_switch",
        "SPDT Switch",
        C.PASSIVE,
        pins(("com", P.PASSIVE), ("no", P.PASSIVE), ("nc", P.PASSIVE)),
        subcategory="switch",
        description="Single-pole double-throw; COM routes to NO or NC",
        default_params={"position": 0},
        tags=["interactive"],
    ),
    component(
        "slide_switch",
        "Slide Switch (SPDT)",
        C.PASSIVE,
        pins(("com", P.PASSIVE), ("1", P.PASSIVE), ("2", P.PASSIVE)),
        subcategory="switch",
        description="Latching slide switch; COM routes to 1 or 2",
        default_params={"position": 0},
        tags=["interactive"],
    ),
    component(
        "dip_switch_4",
        "DIP Switch (4-way)",
        C.PASSIVE,
        pins(
            ("1a", P.PASSIVE),
            ("1b", P.PASSIVE),
            ("2a", P.PASSIVE),
            ("2b", P.PASSIVE),
            ("3a", P.PASSIVE),
            ("3b", P.PASSIVE),
            ("4a", P.PASSIVE),
            ("4b", P.PASSIVE),
        ),
        subcategory="switch",
        description="Four independent SPST switches (bitmask `switches`)",
        default_params={"switches": 0},
        tags=["interactive"],
    ),
]

SEMICONDUCTORS = [
    component(
        "npn_bjt",
        "NPN Transistor",
        C.SEMICONDUCTOR,
        BJT,
        subcategory="transistor",
        default_params={"model": "2N2222", "bf": 150},
    ),
    component(
        "pnp_bjt",
        "PNP Transistor",
        C.SEMICONDUCTOR,
        BJT,
        subcategory="transistor",
        default_params={"model": "2N2907", "bf": 150},
    ),
    component(
        "nmos",
        "N-Channel MOSFET",
        C.SEMICONDUCTOR,
        FET,
        subcategory="transistor",
        default_params={"model": "2N7000", "vth": 2.0},
    ),
    component(
        "pmos",
        "P-Channel MOSFET",
        C.SEMICONDUCTOR,
        FET,
        subcategory="transistor",
        default_params={"model": "BS250", "vth": 2.0},
    ),
    component(
        "zener_diode",
        "Zener Diode",
        C.SEMICONDUCTOR,
        DIODE,
        subcategory="diode",
        default_params={"vz": 5.1},
    ),
]

POWER = [
    component(
        "ground",
        "Ground",
        C.POWER,
        pins(("gnd", P.GROUND)),
        subcategory="reference",
        description="0 V reference node",
        tags=["basic"],
    ),
    component(
        "battery_lipo",
        "LiPo Cell",
        C.POWER,
        pins(("+", P.POWER), ("-", P.GROUND)),
        subcategory="source",
        default_params={"voltage": 3.7, "capacity_mah": 1000},
    ),
    component(
        "dc_supply",
        "DC Power Supply",
        C.POWER,
        pins(("+", P.POWER), ("-", P.GROUND)),
        subcategory="source",
        default_params={"voltage": 5.0},
        tags=["basic"],
    ),
    component(
        "tp4056_charger",
        "TP4056 Charger",
        C.POWER,
        pins(("in+", P.POWER), ("in-", P.GROUND), ("bat+", P.POWER), ("bat-", P.GROUND)),
        subcategory="charging",
        description="1S Li-ion/LiPo charge controller (4.2 V)",
    ),
    component(
        "bms_1s",
        "1S BMS Protection",
        C.POWER,
        pins(("b+", P.POWER), ("b-", P.GROUND), ("p+", P.POWER), ("p-", P.GROUND)),
        subcategory="charging",
        description="Disconnects the pack outside 2.5 V - 4.3 V",
    ),
    component(
        "ina219",
        "INA219 Power Monitor",
        C.POWER,
        pins(
            ("vcc", P.POWER),
            ("gnd", P.GROUND),
            ("scl", P.INPUT),
            ("sda", P.BIDIRECTIONAL),
            ("vin+", P.PASSIVE),
            ("vin-", P.PASSIVE),
        ),
        subcategory="monitor",
        default_params={"i2c_addr": "0x40"},
        tags=["iot"],
    ),
    component(
        "buck_converter",
        "Buck Converter",
        C.POWER,
        REGULATOR,
        subcategory="regulator",
        default_params={"vout": 3.3},
    ),
    component(
        "boost_converter",
        "Boost Converter",
        C.POWER,
        REGULATOR,
        subcategory="regulator",
        default_params={"vout": 5.0},
    ),
    component(
        "ldo_regulator",
        "LDO Regulator",
        C.POWER,
        REGULATOR,
        subcategory="regulator",
        default_params={"vout": 3.3, "dropout": 1.1, "model": "AMS1117"},
    ),
]

ACTUATORS = [
    component(
        "dc_fan",
        "DC Fan",
        C.ACTUATOR,
        POLAR,
        subcategory="motor",
        default_params={"resistance": 60, "rated_current": 0.08},
    ),
    component(
        "buzzer",
        "Buzzer",
        C.ACTUATOR,
        POLAR,
        subcategory="sound",
        default_params={"resistance": 40},
    ),
    component(
        "speaker",
        "Speaker",
        C.ACTUATOR,
        POLAR,
        subcategory="sound",
        default_params={"resistance": 32, "frequency": 440},
    ),
    component(
        "relay",
        "Relay Module",
        C.ACTUATOR,
        pins(
            ("coil+", P.INPUT),
            ("coil-", P.GROUND),
            ("com", P.PASSIVE),
            ("no", P.PASSIVE),
            ("nc", P.PASSIVE),
        ),
        subcategory="switch",
        description="SPDT relay; energize the coil to switch COM from NC to NO",
        default_params={"coil_resistance": 120, "pull_in": 2.5},
    ),
]
