from __future__ import annotations

from app.domain.entities.component import ComponentCategory as C
from app.seed.catalog.builder import P, component, pins

GATE_2 = pins(("a", P.INPUT), ("b", P.INPUT), ("out", P.OUTPUT))
FLOP_OUT = (("q", P.OUTPUT), ("qn", P.OUTPUT))

_GATES = [
    ("and", "AND Gate", "74HC08"),
    ("or", "OR Gate", "74HC32"),
    ("nand", "NAND Gate", "74HC00"),
    ("nor", "NOR Gate", "74HC02"),
    ("xor", "XOR Gate", "74HC86"),
    ("xnor", "XNOR Gate", "74HC266"),
]

LOGIC = [
    component(
        "input",
        "Logic Switch",
        C.LOGIC,
        pins(("out", P.OUTPUT)),
        subcategory="io",
        default_params={"value": 0},
        tags=["digital", "interactive"],
    ),
    component(
        "output", "Logic Probe", C.LOGIC, pins(("in", P.INPUT)), subcategory="io", tags=["digital"]
    ),
    component(
        "clock",
        "Clock",
        C.LOGIC,
        pins(("out", P.OUTPUT)),
        subcategory="timing",
        description="Square wave; period in ticks",
        default_params={"period": 2},
        tags=["digital"],
    ),
    *(
        component(
            key,
            name,
            C.LOGIC,
            GATE_2,
            subcategory="gate",
            default_params={"chip": chip},
            tags=["digital"],
        )
        for key, name, chip in _GATES
    ),
    component(
        "not",
        "NOT Gate",
        C.LOGIC,
        pins(("in", P.INPUT), ("out", P.OUTPUT)),
        subcategory="gate",
        default_params={"chip": "74HC04"},
        tags=["digital"],
    ),
    component(
        "mux2",
        "2:1 Multiplexer",
        C.LOGIC,
        pins(("a", P.INPUT), ("b", P.INPUT), ("sel", P.INPUT), ("out", P.OUTPUT)),
        subcategory="combinational",
        default_params={"chip": "74HC157"},
        tags=["digital"],
    ),
    component(
        "dff",
        "D Flip-Flop",
        C.LOGIC,
        pins(("d", P.INPUT), ("clk", P.INPUT), *FLOP_OUT),
        subcategory="sequential",
        default_params={"chip": "74HC74", "initial": 0},
        tags=["digital"],
    ),
    component(
        "tff",
        "T Flip-Flop",
        C.LOGIC,
        pins(("t", P.INPUT), ("clk", P.INPUT), *FLOP_OUT),
        subcategory="sequential",
        default_params={"chip": "74HC73", "initial": 0},
        tags=["digital"],
    ),
    component(
        "jkff",
        "JK Flip-Flop",
        C.LOGIC,
        pins(("j", P.INPUT), ("k", P.INPUT), ("clk", P.INPUT), *FLOP_OUT),
        subcategory="sequential",
        default_params={"chip": "74HC109", "initial": 0},
        tags=["digital"],
    ),
    component(
        "buffer",
        "Buffer",
        C.LOGIC,
        pins(("in", P.INPUT), ("out", P.OUTPUT)),
        subcategory="gate",
        default_params={"chip": "74HC125"},
        tags=["digital"],
    ),
    component(
        "tristate",
        "Tri-State Buffer",
        C.LOGIC,
        pins(("in", P.INPUT), ("en", P.INPUT), ("out", P.OUTPUT)),
        subcategory="gate",
        description="Drives out only when EN is high, else high-impedance",
        default_params={"chip": "74HC125"},
        tags=["digital"],
    ),
    component(
        "half_adder",
        "Half Adder",
        C.LOGIC,
        pins(("a", P.INPUT), ("b", P.INPUT), ("sum", P.OUTPUT), ("cout", P.OUTPUT)),
        subcategory="arithmetic",
        tags=["digital"],
    ),
    component(
        "full_adder",
        "Full Adder",
        C.LOGIC,
        pins(
            ("a", P.INPUT),
            ("b", P.INPUT),
            ("cin", P.INPUT),
            ("sum", P.OUTPUT),
            ("cout", P.OUTPUT),
        ),
        subcategory="arithmetic",
        tags=["digital"],
    ),
    component(
        "comparator",
        "1-bit Comparator",
        C.LOGIC,
        pins(
            ("a", P.INPUT),
            ("b", P.INPUT),
            ("eq", P.OUTPUT),
            ("gt", P.OUTPUT),
            ("lt", P.OUTPUT),
        ),
        subcategory="arithmetic",
        default_params={"chip": "74HC85"},
        tags=["digital"],
    ),
    component(
        "mux4",
        "4:1 Multiplexer",
        C.LOGIC,
        pins(
            ("i0", P.INPUT),
            ("i1", P.INPUT),
            ("i2", P.INPUT),
            ("i3", P.INPUT),
            ("s0", P.INPUT),
            ("s1", P.INPUT),
            ("out", P.OUTPUT),
        ),
        subcategory="combinational",
        default_params={"chip": "74HC153"},
        tags=["digital"],
    ),
    component(
        "demux4",
        "1:4 Demultiplexer",
        C.LOGIC,
        pins(
            ("in", P.INPUT),
            ("s0", P.INPUT),
            ("s1", P.INPUT),
            ("y0", P.OUTPUT),
            ("y1", P.OUTPUT),
            ("y2", P.OUTPUT),
            ("y3", P.OUTPUT),
        ),
        subcategory="combinational",
        default_params={"chip": "74HC139"},
        tags=["digital"],
    ),
    component(
        "decoder2to4",
        "2:4 Decoder",
        C.LOGIC,
        pins(
            ("a0", P.INPUT),
            ("a1", P.INPUT),
            ("en", P.INPUT),
            ("y0", P.OUTPUT),
            ("y1", P.OUTPUT),
            ("y2", P.OUTPUT),
            ("y3", P.OUTPUT),
        ),
        subcategory="combinational",
        default_params={"chip": "74HC139"},
        tags=["digital"],
    ),
    component(
        "encoder4to2",
        "4:2 Priority Encoder",
        C.LOGIC,
        pins(
            ("i0", P.INPUT),
            ("i1", P.INPUT),
            ("i2", P.INPUT),
            ("i3", P.INPUT),
            ("a0", P.OUTPUT),
            ("a1", P.OUTPUT),
            ("valid", P.OUTPUT),
        ),
        subcategory="combinational",
        default_params={"chip": "74HC148"},
        tags=["digital"],
    ),
    component(
        "srff",
        "SR Flip-Flop",
        C.LOGIC,
        pins(("s", P.INPUT), ("r", P.INPUT), ("clk", P.INPUT), *FLOP_OUT),
        subcategory="sequential",
        default_params={"chip": "74HC279", "initial": 0},
        tags=["digital"],
    ),
    component(
        "counter4",
        "4-bit Counter",
        C.LOGIC,
        pins(
            ("clk", P.INPUT),
            ("reset", P.INPUT),
            ("q0", P.OUTPUT),
            ("q1", P.OUTPUT),
            ("q2", P.OUTPUT),
            ("q3", P.OUTPUT),
        ),
        subcategory="sequential",
        description="Synchronous 4-bit up-counter; reset is sampled on the clock edge",
        default_params={"chip": "74HC161"},
        tags=["digital"],
    ),
    component(
        "shift8",
        "8-bit Shift Register",
        C.LOGIC,
        pins(
            ("clk", P.INPUT),
            ("data", P.INPUT),
            ("q0", P.OUTPUT),
            ("q1", P.OUTPUT),
            ("q2", P.OUTPUT),
            ("q3", P.OUTPUT),
            ("q4", P.OUTPUT),
            ("q5", P.OUTPUT),
            ("q6", P.OUTPUT),
            ("q7", P.OUTPUT),
        ),
        subcategory="sequential",
        description="Serial-in parallel-out; shifts on the clock edge",
        default_params={"chip": "74HC595"},
        tags=["digital"],
    ),
    component(
        "register4",
        "4-bit Register",
        C.LOGIC,
        pins(
            ("clk", P.INPUT),
            ("en", P.INPUT),
            ("d0", P.INPUT),
            ("d1", P.INPUT),
            ("d2", P.INPUT),
            ("d3", P.INPUT),
            ("q0", P.OUTPUT),
            ("q1", P.OUTPUT),
            ("q2", P.OUTPUT),
            ("q3", P.OUTPUT),
        ),
        subcategory="sequential",
        description="Latches D0-D3 on the clock edge when EN is high",
        default_params={"chip": "74HC173"},
        tags=["digital"],
    ),
    component(
        "alu4",
        "4-bit ALU",
        C.LOGIC,
        pins(
            *((f"a{i}", P.INPUT) for i in range(4)),
            *((f"b{i}", P.INPUT) for i in range(4)),
            ("op0", P.INPUT),
            ("op1", P.INPUT),
            ("op2", P.INPUT),
            ("cin", P.INPUT),
            *((f"y{i}", P.OUTPUT) for i in range(4)),
            ("cout", P.OUTPUT),
            ("zero", P.OUTPUT),
        ),
        subcategory="arithmetic",
        description="op: 0 add, 1 sub, 2 and, 3 or, 4 xor, 5 not, 6 shl, 7 shr",
        tags=["digital", "cpu"],
    ),
    component(
        "rom16",
        "16x4 ROM",
        C.LOGIC,
        pins(
            *((f"a{i}", P.INPUT) for i in range(4)),
            *((f"d{i}", P.OUTPUT) for i in range(4)),
        ),
        subcategory="memory",
        description="Contents from the 'data' param (list of up to 16 nibbles)",
        default_params={"data": []},
        tags=["digital", "cpu"],
    ),
    component(
        "ram16",
        "16x4 RAM",
        C.LOGIC,
        pins(
            *((f"a{i}", P.INPUT) for i in range(4)),
            *((f"d{i}", P.INPUT) for i in range(4)),
            ("we", P.INPUT),
            ("clk", P.INPUT),
            *((f"q{i}", P.OUTPUT) for i in range(4)),
        ),
        subcategory="memory",
        description="Async read; writes D0-D3 to the address on the clock edge when WE is high",
        tags=["digital", "cpu"],
    ),
]
