import { build, type Example } from "./build";

export const DIGITAL_EXAMPLES: Example[] = [
  {
    id: "and-or-not",
    title: "Gate playground",
    category: "Digital",
    description: "Two switches feeding AND, OR and XOR probes",
    circuit: build(
      [
        ["A", "input", 0, 0, { value: 1 }],
        ["B", "input", 0, 140, { value: 0 }],
        ["G1", "and", 200, -30],
        ["G2", "or", 200, 120],
        ["G3", "xor", 200, 270],
        ["Y1", "output", 400, 0],
        ["Y2", "output", 400, 150],
        ["Y3", "output", 400, 300],
      ],
      [
        ["A:out", "G1:a"],
        ["B:out", "G1:b"],
        ["A:out", "G2:a"],
        ["B:out", "G2:b"],
        ["A:out", "G3:a"],
        ["B:out", "G3:b"],
        ["G1:out", "Y1:in"],
        ["G2:out", "Y2:in"],
        ["G3:out", "Y3:in"],
      ],
    ),
  },
  {
    id: "full-adder",
    title: "1-bit full adder",
    category: "Digital",
    description: "Sum and carry from A, B and Cin built out of gates",
    circuit: build(
      [
        ["A", "input", 0, 0, { value: 1 }],
        ["B", "input", 0, 120, { value: 1 }],
        ["CIN", "input", 0, 240, { value: 0 }],
        ["X1", "xor", 200, 30],
        ["X2", "xor", 420, 90],
        ["A1", "and", 200, 200],
        ["A2", "and", 420, 240],
        ["O1", "or", 620, 210],
        ["SUM", "output", 620, 90],
        ["COUT", "output", 800, 210],
      ],
      [
        ["A:out", "X1:a"],
        ["B:out", "X1:b"],
        ["X1:out", "X2:a"],
        ["CIN:out", "X2:b"],
        ["X2:out", "SUM:in"],
        ["A:out", "A1:a"],
        ["B:out", "A1:b"],
        ["X1:out", "A2:a"],
        ["CIN:out", "A2:b"],
        ["A1:out", "O1:a"],
        ["A2:out", "O1:b"],
        ["O1:out", "COUT:in"],
      ],
    ),
  },
  {
    id: "nand-latch",
    title: "SR latch (NAND)",
    category: "Digital",
    description: "Cross-coupled NAND gates hold a bit — flip Set/Reset",
    circuit: build(
      [
        ["S", "input", 0, 0, { value: 1 }],
        ["R", "input", 0, 180, { value: 1 }],
        ["N1", "nand", 220, 20],
        ["N2", "nand", 220, 150],
        ["Q", "output", 440, 20],
        ["QN", "output", 440, 150],
      ],
      [
        ["S:out", "N1:a"],
        ["R:out", "N2:b"],
        ["N1:out", "N2:a"],
        ["N2:out", "N1:b"],
        ["N1:out", "Q:in"],
        ["N2:out", "QN:in"],
      ],
    ),
  },
  {
    id: "ripple-counter",
    title: "4-bit ripple counter",
    category: "Digital",
    description: "Four T flip-flops divide the clock — a binary counter",
    circuit: build(
      [
        ["CLK", "clock", 0, 0, { period: 2 }],
        ["ON", "input", 0, 150, { value: 1 }],
        ["T0", "tff", 180, 20],
        ["N0", "not", 340, 150],
        ["T1", "tff", 480, 20],
        ["N1", "not", 640, 150],
        ["T2", "tff", 780, 20],
        ["N2", "not", 940, 150],
        ["T3", "tff", 1080, 20],
        ["Q0", "output", 300, -70],
        ["Q1", "output", 600, -70],
        ["Q2", "output", 900, -70],
        ["Q3", "output", 1200, -30],
      ],
      [
        ["CLK:out", "T0:clk"],
        ["ON:out", "T0:t"],
        ["ON:out", "T1:t"],
        ["ON:out", "T2:t"],
        ["ON:out", "T3:t"],
        ["T0:q", "N0:in"],
        ["N0:out", "T1:clk"],
        ["T1:q", "N1:in"],
        ["N1:out", "T2:clk"],
        ["T2:q", "N2:in"],
        ["N2:out", "T3:clk"],
        ["T0:q", "Q0:in"],
        ["T1:q", "Q1:in"],
        ["T2:q", "Q2:in"],
        ["T3:q", "Q3:in"],
      ],
    ),
    options: { ticks: 24 },
  },
  {
    id: "mux-demo",
    title: "2:1 multiplexer",
    category: "Digital",
    description: "Select routes one of two inputs to the output",
    circuit: build(
      [
        ["A", "input", 0, 0, { value: 1 }],
        ["B", "input", 0, 120, { value: 0 }],
        ["SEL", "input", 0, 240, { value: 0 }],
        ["M1", "mux2", 220, 90],
        ["Y", "output", 430, 110],
      ],
      [
        ["A:out", "M1:a"],
        ["B:out", "M1:b"],
        ["SEL:out", "M1:sel"],
        ["M1:out", "Y:in"],
      ],
    ),
  },
  {
    id: "alu-4bit",
    title: "4-bit ALU",
    category: "Digital",
    description: "A=6, B=3, op=ADD → Y=9; flip the OP switches for sub/and/or/xor/shift",
    circuit: build(
      [
        ["A0", "input", 0, 0, { value: 0 }],
        ["A1", "input", 0, 60, { value: 1 }],
        ["A2", "input", 0, 120, { value: 1 }],
        ["A3", "input", 0, 180, { value: 0 }],
        ["B0", "input", 0, 280, { value: 1 }],
        ["B1", "input", 0, 340, { value: 1 }],
        ["B2", "input", 0, 400, { value: 0 }],
        ["B3", "input", 0, 460, { value: 0 }],
        ["OP0", "input", 0, 560, { value: 0 }],
        ["OP1", "input", 0, 620, { value: 0 }],
        ["OP2", "input", 0, 680, { value: 0 }],
        ["ALU", "alu4", 280, 140],
        ["Y0", "output", 560, 0],
        ["Y1", "output", 560, 60],
        ["Y2", "output", 560, 120],
        ["Y3", "output", 560, 180],
        ["COUT", "output", 560, 270],
        ["ZERO", "output", 560, 330],
      ],
      [
        ["A0:out", "ALU:a0"],
        ["A1:out", "ALU:a1"],
        ["A2:out", "ALU:a2"],
        ["A3:out", "ALU:a3"],
        ["B0:out", "ALU:b0"],
        ["B1:out", "ALU:b1"],
        ["B2:out", "ALU:b2"],
        ["B3:out", "ALU:b3"],
        ["OP0:out", "ALU:op0"],
        ["OP1:out", "ALU:op1"],
        ["OP2:out", "ALU:op2"],
        ["ALU:y0", "Y0:in"],
        ["ALU:y1", "Y1:in"],
        ["ALU:y2", "Y2:in"],
        ["ALU:y3", "Y3:in"],
        ["ALU:cout", "COUT:in"],
        ["ALU:zero", "ZERO:in"],
      ],
    ),
  },
  {
    id: "sync-counter",
    title: "4-bit counter IC",
    category: "Digital",
    description: "A clock drives the synchronous counter4 — watch Q0-Q3 count up in binary",
    circuit: build(
      [
        ["CLK", "clock", 0, 60, { period: 2 }],
        ["CTR", "counter4", 200, 0],
        ["Q0", "output", 430, -30],
        ["Q1", "output", 430, 30],
        ["Q2", "output", 430, 90],
        ["Q3", "output", 430, 150],
      ],
      [
        ["CLK:out", "CTR:clk"],
        ["CTR:q0", "Q0:in"],
        ["CTR:q1", "Q1:in"],
        ["CTR:q2", "Q2:in"],
        ["CTR:q3", "Q3:in"],
      ],
    ),
    options: { ticks: 24 },
  },
];
